name: Generate PDF

on:
  repository_dispatch:
    types: [generate-pdf]
  workflow_dispatch:
    inputs:
      html_content:
        description: "HTML content to convert"
        required: true
        default: "<html><body><h1>Test</h1></body></html>"
      client_name:
        description: "Client name for PDF filename"
        required: false
        default: "DefaultClient"

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload
        env:
          EVENT_TYPE: ${{ github.event.action }}
          CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Event type: $EVENT_TYPE"
          echo "Client payload: $CLIENT_PAYLOAD"

      - name: Set client name
        id: client_info
        run: |
          # Get client name from payload or manual input
          CLIENT_NAME="${{ github.event.client_payload.Client_Name != null && github.event.client_payload.Client_Name || github.event.inputs.client_name || 'DefaultClient' }}"
          
          # Sanitize client name for filename (remove special characters, spaces, etc.)
          SANITIZED_NAME=$(echo "$CLIENT_NAME" | sed 's/[^a-zA-Z0-9._-]/_/g')
          
          # Create the PDF filename
          PDF_FILENAME="Rapport_Identifiants_Client_${SANITIZED_NAME}.pdf"
          
          echo "client_name=$CLIENT_NAME" >> $GITHUB_OUTPUT
          echo "sanitized_name=$SANITIZED_NAME" >> $GITHUB_OUTPUT
          echo "pdf_filename=$PDF_FILENAME" >> $GITHUB_OUTPUT
          
          echo "Client Name: $CLIENT_NAME"
          echo "Sanitized Name: $SANITIZED_NAME"
          echo "PDF Filename: $PDF_FILENAME"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Playwright
        run: |
          npm install playwright
          npx playwright install chromium

      - name: Create PDF generation script
        run: |
          cat > generate-pdf.js << 'EOF'
          const fs = require('fs');
          const { chromium } = require('playwright');

          (async () => {
            try {
              const html = process.env.HTML_CONTENT;
              const outputFilename = process.env.PDF_FILENAME || 'output.pdf';
              
              if (!html) {
                console.error('No HTML content provided');
                process.exit(1);
              }
              
              console.log('HTML content length:', html.length);
              console.log('Output filename:', outputFilename);
              
              const browser = await chromium.launch();
              const page = await browser.newPage();
              
              // Enhanced HTML wrapper with better styles
              const wrappedHTML = `
              <!DOCTYPE html>
              <html>
              <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <style>
                      * { box-sizing: border-box; }
                      body { 
                          margin: 0; 
                          padding: 20px; 
                          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                          line-height: 1.6;
                          color: #333;
                          background: white;
                      }
                      img { max-width: 100%; height: auto; }
                      table { width: 100%; border-collapse: collapse; }
                      th, td { padding: 8px; text-align: left; }
                  </style>
              </head>
              <body>
                  ${html}
              </body>
              </html>
              `;
              
              await page.setContent(wrappedHTML, { waitUntil: 'networkidle' });
              
              const pdfBuffer = await page.pdf({
                format: 'A4',
                printBackground: true,
                margin: { 
                  top: '20mm', 
                  right: '20mm', 
                  bottom: '20mm', 
                  left: '20mm' 
                }
              });
              
              await browser.close();
              
              fs.writeFileSync(outputFilename, pdfBuffer);
              console.log('PDF generated successfully:', outputFilename, 'size:', pdfBuffer.length, 'bytes');
              
            } catch (error) {
              console.error('Error generating PDF:', error);
              process.exit(1);
            }
          })();
          EOF

      - name: Generate PDF
        env:
          HTML_CONTENT: ${{ github.event.client_payload.html_content != null && github.event.client_payload.html_content || github.event.inputs.html_content }}
          PDF_FILENAME: ${{ steps.client_info.outputs.pdf_filename }}
        run: node generate-pdf.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.client_info.outputs.pdf_filename }}
          path: ${{ steps.client_info.outputs.pdf_filename }}

      - name: Notify webhook
        if: success()
        run: |
          CLIENT_NAME="${{ steps.client_info.outputs.client_name }}"
          CLIENT_PROJECT="${{ github.event.client_payload.Client_Project }}"
          CLIENT_EMAIL="${{ github.event.client_payload.Client_Email }}"
          CLIENT_ID="${{ github.event.client_payload.Client_Id }}"
          PDF_FILENAME="${{ steps.client_info.outputs.pdf_filename }}"

          if [ -n "${{ secrets.N8N_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
              -H "Authorization: Bearer ${{ secrets.N8N_WEBHOOK_SECRET }}" \
              -F "pdf=@$PDF_FILENAME" \
              -F "status=success" \
              -F "Client_Name=$CLIENT_NAME" \
              -F "Client_Project=$CLIENT_PROJECT" \
              -F "Client_Email=$CLIENT_EMAIL" \
              -F "Client_Id=$CLIENT_ID" \
              -F "PDF_Filename=$PDF_FILENAME"
          fi
